Paginated table view
wolox-training/gm-swift pull request #4
Opened 2018-08-24 14:23 UTC by gmazzei

## Summary ##

**Trello card**: https://trello.com/c/lg6Y0s3K

Library Tab: Book table uses pagination when the user scrolls down.

## Screenshots ##

### iPhone 5c/5/5s

![5s](https://user-images.githubusercontent.com/2488877/44589530-28b65500-a78f-11e8-99bf-d57d1c6951b5.png)

### iPhone 6/7

![7](https://user-images.githubusercontent.com/2488877/44589538-2f44cc80-a78f-11e8-8fac-e76fd75fc159.png)

### iPhone 6+/7+

![7](https://user-images.githubusercontent.com/2488877/44589544-353aad80-a78f-11e8-9600-288f5b7e889f.png)

## Screencast ##

![pagination](https://user-images.githubusercontent.com/2488877/44589746-b7c36d00-a78f-11e8-8aec-83db51429d3b.gif)

## Known issues ##

No known issue to report

2018-08-27 21:24 UTC, aducret requested changes

2018-08-27 21:24 UTC, aducret commented on WBooks/Library/LibraryViewModel.swift
> +                self.thereAreMoreBooks = loadedBooks.count == LibraryViewModel.amountPerPage
hmm I don't understand this flag. Why are you checking loadedBooks.count with amountPerPage?

2018-08-28 11:58 UTC, gmazzei commented on WBooks/Library/LibraryViewModel.swift
> +                self.thereAreMoreBooks = loadedBooks.count == LibraryViewModel.amountPerPage
If the number of books I just got is the same size as the amount of the page, I suppose that there are probably more books to load (although I don't know for sure). If I don't do that, the app will make a request every time I reach the end of the table, despite the fact that there are no more books.

2018-08-28 12:07 UTC, gmazzei commented on WBooks/Library/LibraryViewModel.swift
> +                self.thereAreMoreBooks = loadedBooks.count == LibraryViewModel.amountPerPage
Of course, there is a better way to solve this but I would need an endpoint like this: /books?from=1&to=31. In that case I could fetch N+1 items and add N to the list, checking the existence of more books with the "+1". 
But the endpoint in this case is /books?page=1&amount=30, making that more difficult to do.

2018-08-28 12:53 UTC, aducret commented on WBooks/Library/LibraryViewModel.swift
> +                self.thereAreMoreBooks = loadedBooks.count == LibraryViewModel.amountPerPage
Ok, please check if the endpoint returns a `Bool` to indicate if there are more books. If not what you did its ok to avoid this issue.

2018-08-28 12:54 UTC, aducret approved these changes

2018-08-28 15:02 UTC, gmazzei commented on WBooks/Library/LibraryViewModel.swift
> +                self.thereAreMoreBooks = loadedBooks.count == LibraryViewModel.amountPerPage
Ok, I didn't find any bool so I'll merge.

2018-08-28 15:07 UTC, merged