Rentals
wolox-training/gm-swift pull request #5
Opened 2018-08-24 16:50 UTC by gmazzei

## Summary ##

**Trello card**: https://trello.com/c/tMrXvRxM

This update adds the content of the "Rentals" tab. It shows a table (the books that the user has rented) and a collection of suggested books.

## Screenshots ##

### iPhone 5c/5/5s

![simulator screen shot - iphone 5s - 2018-08-24 at 13 39 21](https://user-images.githubusercontent.com/2488877/44596617-3f66a700-a7a3-11e8-92ae-a1d387860a74.png)

### iPhone 6/7

![simulator screen shot - iphone 7 - 2018-08-24 at 11 34 36](https://user-images.githubusercontent.com/2488877/44596630-4988a580-a7a3-11e8-8d8f-e85a3d09e8bc.png)

### iPhone 6+/7+

![simulator screen shot - iphone 7 plus - 2018-08-24 at 11 32 55](https://user-images.githubusercontent.com/2488877/44596638-52797700-a7a3-11e8-8221-4406d838536f.png)

## Screencast ##

No screencast necessary.

## Known issues ##

There is an issue when the app runs on iPhone 5s: The table shows two rows instead of one. I haven't found the solution yet but I plan to look it up later.

2018-08-27 21:21 UTC, aducret requested changes

2018-08-27 21:21 UTC, aducret commented on WBooks/Extensions/UIViewControllerExtension.swift
> +    func removeNavigationBarStyle() {
Why is this needed? I think if you setup an style on a navigation bar is not necessary remove it on the `viewWillDissapear`.

2018-08-28 12:13 UTC, gmazzei commented on WBooks/Extensions/UIViewControllerExtension.swift
> +    func removeNavigationBarStyle() {
Yes, it's not really necessary, I will remove it.

2018-08-28 12:51 UTC, aducret approved these changes

2018-08-28 14:44 UTC, merged